// Demo data for PRISM demonstration (Dec 18, 2025)

export const demoOpportunities = [
  {
    id: 'opp_1',
    title: 'Essence: Feature on Women Founders',
    summary: 'Essence Magazine is creating a special feature highlighting women founders who are breaking barriers in their industries. Photo shoot and interview included.',
    mediaType: 'Feature Article',
    outletName: 'Essence Magazine',
    opportunityType: 'PR',
    deadline: '2025-10-30',
    status: 'New!',
    responseState: 'interested',
    clientId: 'client_1',
    clientName: 'Throne Society',
  },
  {
    id: 'opp_2',
    title: 'Fast Company: PR Tech Innovation',
    summary: 'Fast Company is looking for innovative PR tech companies to feature in their technology innovation series. Includes company profile and founder interview.',
    mediaType: 'Innovation Profile',
    outletName: 'Fast Company',
    opportunityType: 'PR',
    deadline: '2025-10-31',
    status: 'New!',
    responseState: 'interested',
    clientId: 'client_2',
    clientName: 'AOPR',
  },
  {
    id: 'opp_3',
    title: 'Forbes: Expert Commentary on Small Business AI',
    summary: 'Forbes is seeking expert commentary on the impact of AI on small businesses. This is a written contribution opportunity with potential for author byline.',
    mediaType: 'Expert Commentary',
    outletName: 'Forbes',
    opportunityType: 'PR',
    deadline: '2025-10-29',
    status: 'Accepted',
    responseState: 'accepted',
    clientId: 'client_2',
    clientName: 'AOPR',
  },
  {
    id: 'opp_4',
    title: 'TechCrunch: AI in Marketing Panel',
    summary: 'Panel discussion at TechCrunch Disrupt on AI innovation in marketing and PR. 45-minute session with Q&A. Travel and accommodation covered.',
    mediaType: 'Speaking Engagement',
    outletName: 'TechCrunch',
    opportunityType: 'Event',
    deadline: '2025-11-11',
    status: 'Interested',
    responseState: 'interested',
    clientId: 'client_3',
    clientName: 'Sophia Chen',
  },
  {
    id: 'opp_5',
    title: 'Vogue Business: Sustainability in Fashion Tech',
    summary: 'Long-form podcast interview about sustainability initiatives in fashion technology. Remote recording, 1 hour commitment.',
    mediaType: 'Podcast',
    outletName: 'Vogue Business',
    opportunityType: 'PR',
    deadline: '2025-11-17',
    status: 'New!',
    responseState: 'pending',
    clientId: 'client_1',
    clientName: 'Throne Society',
  },
  {
    id: 'opp_6',
    title: 'BBC Radio 4: Future of Entrepreneurship',
    summary: 'Live radio interview discussing emerging trends in entrepreneurship. 15-minute segment during morning show with national reach.',
    mediaType: 'Radio Interview',
    outletName: 'BBC Radio 4',
    opportunityType: 'PR',
    deadline: '2025-11-13',
    status: 'Accepted',
    responseState: 'accepted',
    clientId: 'client_4',
    clientName: 'Elena Rodriguez',
  },
];

export const demoClients = [
  {
    id: 'client_1',
    name: 'Throne Society',
    industry: 'Fashion Tech',
    primaryContact: 'Aisha Patel',
    email: 'aisha@thronesociety.com',
    responseRate: 85,
  },
  {
    id: 'client_2',
    name: 'AOPR',
    industry: 'PR Technology',
    primaryContact: 'Sarah Johnson',
    email: 'sarah@aopr.com',
    responseRate: 92,
  },
  {
    id: 'client_3',
    name: 'Tech Innovators Inc',
    industry: 'AI Marketing',
    primaryContact: 'Sophia Chen',
    email: 'sophia@techinnovators.com',
    responseRate: 78,
  },
  {
    id: 'client_4',
    name: 'Global Ventures',
    industry: 'Entrepreneurship',
    primaryContact: 'Elena Rodriguez',
    email: 'elena@globalventures.com',
    responseRate: 88,
  },
];

export const demoChatMessages = [
  {
    id: 'msg_1',
    opportunityId: 'opp_1',
    sender: 'client',
    message: 'What are the specific requirements?',
    timestamp: '2025-12-09T20:38:00Z',
  },
  {
    id: 'msg_2',
    opportunityId: 'opp_1',
    sender: 'ai',
    message: 'For this opportunity, we\'ll need a high-resolution headshot, a brief bio (150 words), and your availability for the interview dates. The publication is also requesting 2-3 talking points you\'d like to cover.',
    timestamp: '2025-12-09T20:38:00Z',
    isAiAssisted: true,
  },
  {
    id: 'msg_3',
    opportunityId: 'opp_1',
    sender: 'client',
    message: 'Is there a due date for this to be submitted?',
    timestamp: '2025-12-09T20:39:00Z',
  },
  {
    id: 'msg_4',
    opportunityId: 'opp_1',
    sender: 'ai',
    message: 'That\'s a great question! Let me connect you with the AOPR team member managing this opportunity. They\'ll get back to you within 2 hours with detailed information. In the meantime, is there anything else I can help clarify?',
    timestamp: '2025-12-09T20:39:00Z',
    isAiAssisted: true,
    isEscalated: true,
  },
];

export const demoTasks = [
  {
    id: 'task_1',
    opportunityId: 'opp_3',
    clientId: 'client_2',
    title: 'Schedule media training for Forbes interview',
    description: 'Coordinate with client for media training session before Forbes expert commentary submission.',
    status: 'pending',
    assignedTo: 'Sarah Johnson',
    dueDate: '2025-10-25',
  },
  {
    id: 'task_2',
    opportunityId: 'opp_6',
    clientId: 'client_4',
    title: 'Collect marketing assets for BBC Radio 4',
    description: 'Get high-res headshot and updated bio from Elena for BBC Radio 4 segment.',
    status: 'in_progress',
    assignedTo: 'Michael Brown',
    dueDate: '2025-11-10',
  },
];

export const demoStats = {
  activeOpportunities: 2,
  avgResponseTime: 1.5,
  accepted: 2,
  interested: 2,
  overallResponseRate: 67,
};
